### PR TITLE
fixes and update

### PR DESCRIPTION
**Pull request by gatooooooo**
| + change domain to fdpinfo.github.io
| + remove reborn branding from client title
| + more insults
| + install instructions for the readme.md
| - announcements, it's broken and idk how to fix so its disabled

### CODE REVIEW

**Comment by opZywl** [comment]
Okay @contionability I asked a friend to do this I have (full access) and the links come to the fdp repository because we don't have access to fdpclient.club and the download is breaking for a long time until everything comes back we will use this right

**Comment by opZywl** [comment]
if you think everything is good we use

**Comment by gatooooooo** [comment]
gg

**Comment by gatooooooo** [comment]
@contionability check

**Comment by opZywl** [comment]
@contionability

**Comment by gatooooooo** [comment]
@opZywl he isnt checking

**Pull request merged**
