### PR TITLE
Optimize imports, fix grammar, use Kotlin code style and modify the dark theme main menu a bit

### PR DESCRIPTION
**Pull request by mmvanheusden**
Will need some stability testing before merging, will undraft once i can confirm it's stable

### CODE REVIEW

**Comment by C00LC0D35** [comment]
that goes against the shitcode tag tho

**Comment by C00LC0D35** [comment]
plus, you are messing with every single module, messing up every pull request and merge that is currently in progress. (as well has messing with forks)

**Comment by mmvanheusden** [comment]
also how does this mess up every single pull request just merge it into their branch and voila

**Comment by mmvanheusden** [comment]
also it's just a refactor to improve readability nothing technical is changed except for the dark theme thingy and the title

**Comment by mmvanheusden** [comment]
This is now ready to merge.

**Comment by mmvanheusden** [comment]
you didn't even merge it in the right branch

**Comment by mmvanheusden** [comment]
oh wait i messed it up 💀

**Pull request merged**
