### PR TITLE
use my Elixir version

### PR DESCRIPTION
**Pull request by ghost**
琉璃小姐我爱你 <3

### CODE REVIEW

**Comment by ghost** [comment]
maybe you can delete thealtening, i added it in Elixir

**Comment by ghost** [comment]
i have no time to edit FDPClient's code

**Comment by ghost** [comment]
为什么没人来看我的pr? ;w;

**Comment by gatooooooo** [comment]
sus

**Comment by opZywl** [comment]
hmm

**Comment by ghost** [comment]
sus

**Comment by ReCaree** [comment]
100% rat bonus

**Comment by DinoFengz** [comment]
ra

**Comment by qazwsx-11** [comment]
sus

**Review by JohnShiozo — APPROVED** [review]
looks good 👍

**Comment by gatooooooo** [comment]
send free rat

**Comment by ghost** [comment]
susususususususususus

**Pull request closed without merging**
