### PR TITLE
Rewrite NCPHop with a flagless, stable speed

### PR DESCRIPTION
**Pull request by mmvanheusden**
yessir

### CODE REVIEW

**Comment by DinoFengz** [comment]
my suggest : add back NCPHop. it bypass some server ._.

**Comment by GutatOderSo** [comment]
I'd say, make them both seperate speeds

**Comment by mmvanheusden** [comment]
sure thing one sec

**Comment by mmvanheusden** [comment]
Done

**Comment by mmvanheusden** [comment]
what the fuck why is this once again not merged properly are you retarded

**Pull request merged**
