### PR TITLE
56

### PR DESCRIPTION
**Pull request by afdera**

### CODE REVIEW

**Comment by DinoFengz** [comment]
wtf?

**Comment by hlte-git** [comment]
what i can see here are things that make no sense at all (apart from that weird looking armor class, can guarantee that its skidded)

**Comment by C00LC0D35** [comment]
no thanks
probably 100% skidded
u used 3 commits deleting, readding, and deleting the same two lines of code
NO ONE NEEDS VILLAGER ESP
You are also deleting a good matrix bypass
ur criticals are useless
nothing here is useful imo and every1 o

**Comment by DinoFengz** [comment]
This branch has conflicts that must be resolved

**Pull request closed without merging**
