### PR TITLE
Update NoSlow.kt

### PR DESCRIPTION
**Pull request by K0itoyuu**
better medusa noslow.
fixed using killaura lagback.

### CODE REVIEW

**Comment by InnocentHumanNiko** [comment]
hmm
pretty good

**Comment by InnocentHumanNiko** [comment]
ig

**Comment by DinoFengz** [comment]
C0CInput + C0B stop sprinting ._. better

**Comment by K0itoyuu** [comment]
> C0CInput + C0B stop sprinting ._. better

medusa only check C0B

**Pull request merged**
